apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-kps-prometheus.monitoring.svc.cluster.local:9090
        isDefault: false

      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://monitoring-loki.monitoring.svc.cluster.local:3100
        isDefault: false
